# Generated by Django 3.2.5 on 2021-07-21 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20210721_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='course_id',
            new_name='course',
        ),
    ]
